"""add listing browse index

Revision ID: 45857916da2f
Revises: 8793350091cc
Create Date: 2026-08-10 14:27:18.300671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45857916da2f'
down_revision: Union[str, Sequence[str], None] = '8793350091cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listings_browse', 'listings', ['approval_status', 'is_available', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listings_browse', table_name='listings')
    # ### end Alembic commands ###
