"""baseline existing schema

Revision ID: 8793350091cc
Revises:
Create Date: 2026-08-11 19:12:46.908131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8793350091cc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "full_name",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "phone_number",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "password_hash",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )

    op.create_index(
        op.f("ix_users_id"),
        "users",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_users_phone_number"),
        "users",
        ["phone_number"],
        unique=True,
    )

    op.create_table(
        "listings",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "landlord_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "location",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "monthly_rent",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "bedrooms",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "bathrooms",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "image_url",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "amenities",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "is_approved",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "approval_status",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "rejection_reason",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "rejected_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "rejected_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "last_availability_confirmed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_listings_id"),
        "listings",
        ["id"],
        unique=False,
    )

    op.create_table(
        "conversations",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "listing_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "landlord_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id",
            "tenant_id",
            "landlord_id",
            name=(
                "unique_listing_tenant_"
                "landlord_conversation"
            ),
        ),
    )

    op.create_index(
        op.f("ix_conversations_id"),
        "conversations",
        ["id"],
        unique=False,
    )

    op.create_table(
        "favorites",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "listing_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "listing_id",
            name="unique_tenant_listing_favorite",
        ),
    )

    op.create_index(
        op.f("ix_favorites_id"),
        "favorites",
        ["id"],
        unique=False,
    )

    op.create_table(
        "listing_images",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "listing_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "image_url",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "public_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "is_cover",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_listing_images_id"),
        "listing_images",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f(
            "ix_listing_images_listing_id"
        ),
        "listing_images",
        ["listing_id"],
        unique=False,
    )

    op.create_table(
        "reports",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "listing_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "reporter_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "details",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "reviewed_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id",
            "reporter_id",
            name="unique_listing_reporter",
        ),
    )

    op.create_index(
        op.f("ix_reports_id"),
        "reports",
        ["id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_reports_listing_id"),
        "reports",
        ["listing_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_reports_reporter_id"),
        "reports",
        ["reporter_id"],
        unique=False,
    )

    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "conversation_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "sender_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "read_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_messages_id"),
        "messages",
        ["id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f("ix_messages_id"),
        table_name="messages",
    )
    op.drop_table("messages")

    op.drop_index(
        op.f("ix_reports_reporter_id"),
        table_name="reports",
    )
    op.drop_index(
        op.f("ix_reports_listing_id"),
        table_name="reports",
    )
    op.drop_index(
        op.f("ix_reports_id"),
        table_name="reports",
    )
    op.drop_table("reports")

    op.drop_index(
        op.f(
            "ix_listing_images_listing_id"
        ),
        table_name="listing_images",
    )
    op.drop_index(
        op.f("ix_listing_images_id"),
        table_name="listing_images",
    )
    op.drop_table("listing_images")

    op.drop_index(
        op.f("ix_favorites_id"),
        table_name="favorites",
    )
    op.drop_table("favorites")

    op.drop_index(
        op.f("ix_conversations_id"),
        table_name="conversations",
    )
    op.drop_table("conversations")

    op.drop_index(
        op.f("ix_listings_id"),
        table_name="listings",
    )
    op.drop_table("listings")

    op.drop_index(
        op.f("ix_users_phone_number"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_id"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_email"),
        table_name="users",
    )
    op.drop_table("users")