"""add verified property fields

Revision ID: c76ef3ed80e1
Revises: f51904c3128a
Create Date: 2026-08-21 15:01:37.148961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76ef3ed80e1'
down_revision: Union[str, Sequence[str], None] = 'f51904c3128a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "listings",
        sa.Column(
            "is_verified_property",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "listings",
        sa.Column(
            "property_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "listings",
        sa.Column(
            "property_verified_by",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.create_foreign_key(
        None,
        "listings",
        "users",
        ["property_verified_by"],
        ["id"],
    )

    op.alter_column(
        "listings",
        "is_verified_property",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'property_verified_by')
    op.drop_column('listings', 'property_verified_at')
    op.drop_column('listings', 'is_verified_property')
    # ### end Alembic commands ###
